// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pies.API.DbContexts;

namespace Pies.API.Migrations
{
    [DbContext(typeof(PiesContext))]
    partial class PiesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pies.API.Entities.Pie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PieTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PieTypeId");

                    b.ToTable("Pies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b1c2b4d-48c7-402a-80c3-cc796ad49c6b"),
                            DateCreated = new DateTimeOffset(new DateTime(2020, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 12, 0, 0, 0)),
                            Name = "Mushroom Pie",
                            PieTypeId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            ShopId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = new Guid("d8663e5e-7494-4f81-8739-6e0de1bea7ee"),
                            DateCreated = new DateTimeOffset(new DateTime(2021, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 12, 0, 0, 0)),
                            Name = "Butter Chicken Pie",
                            PieTypeId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            ShopId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = new Guid("d173e20d-159e-4127-9ce9-b0ac2564ad97"),
                            DateCreated = new DateTimeOffset(new DateTime(2019, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 12, 0, 0, 0)),
                            Name = "Steak Pie",
                            PieTypeId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            ShopId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = new Guid("40ff5488-fdab-45b5-bc3a-14302d59869a"),
                            DateCreated = new DateTimeOffset(new DateTime(2020, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 13, 0, 0, 0)),
                            Name = "Apple Pie",
                            PieTypeId = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            ShopId = 2,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Pies.API.Entities.PieType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FlavourTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PieTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            FlavourTypeId = 1,
                            Name = "Mushroom"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            FlavourTypeId = 3,
                            Name = "Butter Chicken"
                        },
                        new
                        {
                            Id = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            FlavourTypeId = 3,
                            Name = "Steak"
                        },
                        new
                        {
                            Id = new Guid("102b566b-ba1f-404c-b2df-e2cde39ade09"),
                            FlavourTypeId = 2,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = new Guid("5b3621c0-7b12-4e80-9c8b-3398cba7ee05"),
                            FlavourTypeId = 2,
                            Name = "Berry"
                        },
                        new
                        {
                            Id = new Guid("2aadd2df-7caf-45ab-9355-7f6332985a87"),
                            FlavourTypeId = 3,
                            Name = "Mexican"
                        },
                        new
                        {
                            Id = new Guid("2ee49fe3-edf2-4f91-8409-3eb25ce6ca51"),
                            FlavourTypeId = 1,
                            Name = "Pork & Apple"
                        });
                });

            modelBuilder.Entity("Pies.API.Entities.Pie", b =>
                {
                    b.HasOne("Pies.API.Entities.PieType", "PieType")
                        .WithMany()
                        .HasForeignKey("PieTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PieType");
                });
#pragma warning restore 612, 618
        }
    }
}
